version: '3.8'

services:

  tensorflow:
    image: tensorflow/serving:2.10.1
    environment:
      MODEL_NAME: punctuation
      MODEL_BASE_PATH: /models
    volumes:  
      - ./data//punctuation/models:/models
    restart: unless-stopped 
    ports:
      - 8501:8501
      - 8500:8500
    