-include Makefile.options.local

TOOLS_ROOT?=../../tools
SCRIPT_DIR=../../ptf
INPUT_FILE?=../../text/BIT_merged_unique.txt
WORK_DIR?=data
SENTENCES?=10000000000 # take all
PUT_DIR=$(USER_SERVER):$(REMOTE_DIR)
