-include Makefile.options.local

TOOLS_ROOT?=../../tools
SCRIPT_DIR=../../ptf
SCRIPT_L_DIR=../bit-prepare2/local
INPUT_FILE?=../../text/BIT_merged_unique.txt
WORK_DIR?=data
SENTENCES?=10000000000 # take all
PUT_DIR=$(USER_SERVER):$(REMOTE_DIR)
MAIN_VOCAB_FILE=../bit-prepare/wrk/final/vocab.txt
MAIN_MODEL_FILE=../model/m1_02.h5

MODEL_PREFIX?=m1
MODEL_TEST?=02
WORD_VEC_SIZE?=256
HIDDEN?=256
GPU?=0
SHUFFLE?=100
PREFETCH?=10
PREFETCH_ON?=
BATCH_SIZE?=128
