-include Makefile.options.local

SCRIPT_DIR=../../ptf/
KALDI_ROOT?=../../../kaldi
TOOLS_ROOT?=../../tools
INPUT_DIR?=../bit-prepare2/final
WORK_DIR?=data
TOP_WORDS?=5000
PUT_DIR=$(USER_SERVER):$(REMOTE_DIR)
maxJobs=4